### ISSUE TITLE
Version switcher seems broken on mobile

### ISSUE THREAD

**Issue by tikkss** [apache/arrow-flight-sql-postgresql#140]
Looks like the `version switcher` on mobile in https://arrow.apache.org/flight-sql-postgresql seems broken.

![image](https://github.com/apache/arrow-flight-sql-postgresql/assets/4122070/e6f47572-1467-4f58-9fb6-477791ae8709)

Maybe, updating to [pydata-sphinx-theme v0.14.0](https://github.com/pydata/pydata-sphinx-theme/releases/tag/v0.14.0) will fix it. Please refer to the following.

- pydata/pydata-sphinx-theme#1340
- pydata/pydata-sphinx-theme#1342

**Comment by kou** [comment]
Oh, good catch!
Then it will be fixed eventually because we don't pin pydata-sphinx-theme: https://github.com/apache/arrow-flight-sql-postgresql/blob/962590425085b3eb8778599b09169934067580a6/doc/requirements.txt#L19

https://arrow.apache.org/flight-sql-postgresql/devel/ will be fixed in the next commit.
https://arrow.apache.org/flight-sql-postgresql/current/ will be fixed in the next release.
But https://arrow.apache.org/flight-sql-postgresql/0.1.0/ unless we don't apply the fix https://github.com/pydata/pydata-sphinx-theme/pull/1342 to https://github.com/apache/arrow-flight-sql-postgresql/blob/asf-site/0.1.0/_static/scripts/pydata-sphinx-theme.js . But the `.js` was minified...

**Comment by tikkss** [comment]
Thank you! I see it works well in the next commit and next release.

> But the `.js` was minified...

Oh, I see that this problem is difficult to resolve.

**Comment by kou** [comment]
Backported.

**Comment by tikkss** [comment]
Wow! That's cool!

[devel website](https://arrow.apache.org/flight-sql-postgresql/devel/) is corrected.
[0.1.0 website](https://arrow.apache.org/flight-sql-postgresql/0.1.0/) is corrected.

[current website](https://arrow.apache.org/flight-sql-postgresql/current/) will be fixed in the next release.

Thanks!
